### ISSUE TITLE
Share to Twitter Button

### ISSUE THREAD

**Issue by saurabhdaware** [uppernauts/year-in-dev#3]
Hi, Such a great app, Cool work! 

I think having a 'Share to Twitter' button would help users to share their stats and it will also increase the chances of user sharing the app!

**Comment by pawap90** [comment]
Great idea! We're thinking about how to approach this. The easiest solution, I believe, would be to create a string that would be sent as a tweet. I'm thinking something like:

"My year in DEV: I wrote N articles. Received X comments and Y reactions. My favorite tags were #tag1 #tag2 #tag3.

https://year-in-dev.cephhi.com/username"

On the other hand, the ideal solution for me would be to take a screenshot of each user's stats and then share the image as a twitter card. But we'd have to store those images somewhere (free) and it'll take longer to build 🤔

Maybe we'll do the easy solution first and see how it goes. What do you think @saurabhdaware  ?

**Comment by saurabhdaware** [comment]
> Maybe we'll do the easy solution first and see how it goes
I agree! I think starting off with text is fine. 

If you plan to implement with images, I think cloudinary has a JavaScript SDK that lets you upload images with the server-side and its free too.

**Comment by pawap90** [comment]
We merged this feature yesterday. Now there's a Share button on the Stats page that generates a tweet intent containing the stats and link to the page.
We also included the username and name of the user in the meta tags so the twitter card would display a custom title and description for each user. This last part may take a week to be available because of how twitter handles card tag information ([more info about this on twitter docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/troubleshooting-cards#refreshing_tags)).

Thanks again @saurabhdaware!
